// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const { user, password, host, port, dbname } = process.env;
const SAFE_PASSWORD = password ? encodeURIComponent(password) : "";
const DATABASE_URL = `postgresql://${user}:${SAFE_PASSWORD}@${host}:${port}/${dbname}?sslmode=require`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
